### ISSUE TITLE
有时候瞬间结束了，并且没有结果

### ISSUE THREAD

**Issue by TZ0385** [alwaystest18/dnsVerifier#1]

**Comment by alwaystest18** [comment]
用项目自带的vaildResolvers_1.0.txt文件会出现这种问题吗，另外可以附一下你使用的命令和dns文件

**Comment by TZ0385** [comment]
自带文件没有出现这种问题
[xxx.zip](https://github.com/alwaystest18/dnsVerifier/files/11740414/xxx.zip)
命令如下：
dnsVerifier.exe -r xxx.txt -o dns.txt

**Comment by alwaystest18** [comment]
开发环境为linux，只考虑了\n换行，windows下换行是\r\n，多出来的\r导致匹配ip格式失败，所以没有识别到，目前已经修复此问题

**Comment by alwaystest18** [comment]
感谢反馈
